config/routes.rb
Rails.application.routes.draw do
   get 'registers/list', to: 'registers#list', as: 'list_register'
   root'registers#list'
   resources :registers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/register.rb
class Register < ApplicationRecord
  #Check FirstName and LastName
  validates :first_name, presence: { message: "กรุณากรอกชื่อ" }
  validates :last_name, presence: { message: "กรุณากรอกนามสกุล" }
  validates :birthday, presence:{message:"กรุณากรอกวันเกิด"}
  validates :gender, presence:{message:"กรุณาเลือกเพศ"}
  validates :email,presence:{message:"กรุณากรอกอีเมล"}
  validates :subject, presence: { message: "กรุณาเลือกวิชา" }

  # ตรวจสอบหมายเลขโทรศัพท์
  validate :phone_validation

  def phone_validation
    if phone.blank?
      errors.add(:phone, "กรุณากรอกหมายเลขโทรศัพท์")
    # ตรวจสอบรูปแบบเบอร์โทรให้ตรงตาม 123-456-7890
    elsif phone !~ /\A\d{3}-\d{3}-\d{4}\z/
      errors.add(:phone, "หมายเลขโทรศัพท์ต้องอยู่ในรูปแบบ xxx-xxx-xxxx")
    elsif phone.length < 12
      errors.add(:phone, "หมายเลขโทรศัพท์ต้องมีอย่างน้อย 10 หลัก (รวมขีดกลาง)")
    end
  end
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  before_action :set_register, only: [:show, :edit, :update, :destroy]

  # GET /registers
  def index
    @registers = Register.all
    @register = Register.new # Initialize @register for the modal form
  end

  # GET /registers/list
  def list
    @registers = Register.all
    @subjects = Register.pluck(:subject).uniq
    @register = Register.new # Initialize @register for the modal form

    if params[:search].present?
      search_term = params[:search].downcase
      @registers = @registers.where("LOWER(first_name) LIKE :term OR LOWER(last_name) LIKE :term", term: "%#{search_term}%")
    end

    if params[:subject].present?
      @registers = @registers.where(subject: params[:subject])
    end
  end

  # POST /registers
  def create
    @register = Register.new(register_params)
    if @register.save
     
      # Respond with JSON for AJAX
      render json: { 
        message: 'User was successfully created.',
        redirect_url: list_register_path
      }, status: :ok
     
    else
      # Respond with validation errors for AJAX
      render json: @register.errors.messages, status: :unprocessable_entity
    end
  end

  # GET /registers/:id/edit
  def edit
    @register = Register.find(params[:id])
  end

  # PATCH/PUT /registers/:id
  def update
    @register = Register.find(params[:id])
    if @register.update(register_params)
      redirect_to list_register_path
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  # DELETE /registers/:id
  def destroy
    @register = Register.find(params[:id])
    @register.destroy
    redirect_to list_register_path, notice: 'User was successfully deleted.'
  end

  private

  def set_register
    @register = Register.find(params[:id])
  end

  def register_params
    params.require(:register).permit(:first_name, :last_name, :birthday, :gender, :email, :phone, :subject)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/registers/_create_modal.html.erb
        <!-- Modal for Creating Users -->
    <div id="createModal" class="modal" data-controller="create">
      <div class="modal-content">
        <h1>Create Users</h1>
        <%= form_with(model: @register, url: registers_path, method: :post, local: false, html: { id: 'reg-form', class: 'reg-form' }) do |form| %>
          <!-- Row First Name and Last Name -->
          <div class="form-row">
            <div class="form-group">
              <%= form.label :first_name, 'First Name' %>
              <%= form.text_field :first_name, class: "form-control", id: "first_name" %>
              <div class="error-message" id="error_first_name"></div>
            </div>
            <div class="form-group">
              <%= form.label :last_name, 'Last Name' %>
              <%= form.text_field :last_name, class: "form-control", id: "last_name" %>
              <div class="error-message" id="error_last_name"></div>
            </div>
          </div>

          <!-- Row Birthday and Gender -->
          <div class="form-row">
            <div class="form-group">
              <%= form.label :birthday, 'Birthday' %>
              <%= form.date_field :birthday, class: "form-control", id: "birthday" %>
              <div class="error-message" id="error_birthday"></div>
            </div>
            <div class="form-group">
              <%= form.label :gender, 'Gender' %>
              <div class="radio-group">
                <%= form.radio_button :gender, "Male", id: "gender_male" %>
                <%= form.label :gender_male, "Male", class: "label-gender", for: "gender_male" %>
                <%= form.radio_button :gender, "Female", id: "gender_female" %>
                <%= form.label :gender_female, "Female", class: "label-gender", for: "gender_female" %>
              </div>
              <div class="error-message" id="error_gender"></div>
            </div>
          </div>

          <!-- Row Email and Phone -->
          <div class="form-row">
            <div class="form-group">
              <%= form.label :email, 'Email' %>
              <%= form.email_field :email, class: "form-control", id: "email" %>
              <div class="error-message" id="error_email"></div>
            </div>
            <div class="form-group">
              <%= form.label :phone, 'Phone Number' %>
              <%= form.telephone_field :phone, class: "form-control", id: "phone", data: { controller: "phone", phone_target: "input" } %>
              <div class="error-message" id="error_phone"></div>
            </div>
          </div>

          <!-- Row Subject -->
          <div class="form-group">
            <%= form.label :subject, 'Subject' %>
            <%= form.select :subject, options_for_select([["Math", "Math"], ["Science", "Science"], ["Ruby", "Ruby"]]), prompt: "Choose option", class: "form-control", id: "subject" %>
            <div class="error-message" id="error_subject"></div>
          </div>

          <!--Button -->
          <div class="row-btn">
            <button type="button" id="cancelCreate" class="btn btn-cancel" data-action="click->create#close_modal">Cancel</button>
            <%= form.submit "Submit", id: "confirmCreate", class: "btn btn-submit", data: { action: "click->create#confirm_create" } %>
          </div>
        <% end %>
      </div>
    </div>

app/views/registers/_delete_modal.html.erb
 <!-- Delete Confirmation Modal -->
<div id="deleteConfirmationModal" class="modal-delete" data-controller="delete">
    <div class="modal-content-delete">
        <p>Are you sure you want to delete this user?</p>
        <div class="row-btn" >
            <button id="confirmDelete" class="btn btn-delete" data-action="click->delete#confirm_delete">Yes, Delete</button>
            <button id="cancelDelete" class="btn btn-cancel" data-action="click->delete#close_modal">No</button>
        </div>
    </div>
</div>

app/views/registers/_form.html.erb
<body class="body-register">
<div class="reg-form-container">

        <%= link_to list_register_path, class: "btn-back-all-users" do %>
          <i class="fas fa-arrow-left"></i> Back
        <% end %>
   
  <%= form_with model: @register, local: true, class: "reg-form" do |form| %>
   <h1>Edit Users</h1>
  <!-- Row First Name and Last Name -->
  <div class="form-row">
    <div class="form-group">
      <%= form.label :first_name, 'First Name' %>
      <%= form.text_field :first_name, class: "form-control", id: "firstName" %>
      <!-- Message error first_name -->
        <% if @register.errors[:first_name].any? %>
       <div class="error-message">
        <%= @register.errors[:first_name].join(", ") %>
        </div>
       <% end %>
    </div>
    <div class="form-group">
      <%= form.label :last_name, 'Last Name' %>
      <%= form.text_field :last_name, class: "form-control", id: "lastName"%>
       <!-- Message error last_name -->
        <% if @register.errors[:last_name].any? %>
       <div class="error-message">
        <%= @register.errors[:last_name].join(", ") %>
        </div>
       <% end %>
    </div>
  </div>

  <!-- Row Birthday and Gender -->
  <div class="form-row">
    <div class="form-group">
      <%= form.label :birthday, 'Birthday' %>
      <%= form.date_field :birthday, class: "form-control", id: "birthday" %>
        <!-- Message error birthday -->
        <% if @register.errors[:birthday].any? %>
        <div class="error-message">
        <%= @register.errors[:birthday].join(", ") %>
        </div>
        <% end %>
    </div>
    <div class="form-group">
      <%= form.label :gender, 'Gender'%>
      <div class="radio-group">
        <%= form.radio_button :gender, "Male", id: "male" %>
        <%= form.label :gender_male, "Male",  class:"label-gender" ,for: "male" %>
        <%= form.radio_button :gender, "Female", id: "female" %>
        <%= form.label :gender_female, "Female", class:"label-gender" ,for: "female" %>
      </div>
      <!-- Message error gender -->
      <% if @register.errors[:gender].any? %>
      <div class="error-message">
      <%= @register.errors[:gender].join(", ") %>
      </div>
      <% end %>
    </div>
  </div>

  <!-- Row Email and Phone -->
  <div class="form-row">
    <div class="form-group">
      <%= form.label :email, 'Email' %>
      <%= form.email_field :email, class: "form-control", id: "email" %>
        <% if @register.errors[:email].any? %>
        <div class="error-message">
        <%= @register.errors[:email].join(", ") %>
        </div>
        <% end %>
    </div>
<div class="form-group">
  <%= form.label :phone, 'Phone Number' %>
  <%= form.telephone_field :phone, class: "form-control", id: "phone", data: { controller: "phone", phone_target: "input" } %>
  
  <% if @register.errors[:phone].any? %>
    <div class="error-message">
      <%= @register.errors[:phone].join(", ") %>
    </div>
  <% end %>
</div>

      </div>

  <!-- Row Subject -->
  <div class="form-group">
    <%= form.label :subject, 'Subject' %>
    <%= form.select :subject, options_for_select([["Math", "Math"], ["Science", "Science"],["Ruby", "Ruby"]]), prompt: "Choose option", class: "form-control", id: "subject" %>
      <% if @register.errors[:subject].any? %>
      <div class="error-message">
      <%= @register.errors[:subject].join(", ") %>
      </div>
      <% end %>
  </div>

  <!-- Submit Button -->
  <div class="form-group">
    <%= form.submit "Update", class: "btn btn-submit" %>
  </div>
   
</div>
<body>
<% end %>

app/views/registers/edit.html.erb
<%= render "form", register: @register %>

app/views/registers/index.html.erb
<body class="body-home" data-controller="create">
  <div class="container-home">
    <!-- Navigation Section -->
    <div class="header">
      <h1>User Management</h1>
      <p>Manage your users efficiently by creating new users or viewing the list of all registered users.</p>
    </div>

    <!-- Action Buttons -->
    <div class="action-buttons">
      <!-- Create Users Button -->
      <button type="button" class="btn btn-add" data-action="click->create#show_modal">
        <i class="fas fa-user-plus"></i> Create Users
      </button>

      <!-- View All Users Button -->
      <div class="action-link">
        <%= link_to list_register_path, class: "btn btn-info btn-large" do %>
          <i class="fas fa-users"></i> All Users
        <% end %>
      </div>
    </div>

    <!-- Modal for Creating Users -->
    <div id="createModal" class="modal" data-controller="create">
      <div class="modal-content">
        <h1>Create Users</h1>
        <%= form_with(model: @register, url: registers_path, method: :post, local: false, html: { id: 'reg-form', class: 'reg-form' }) do |form| %>
          <!-- Row First Name and Last Name -->
          <div class="form-row">
            <div class="form-group">
              <%= form.label :first_name, 'First Name' %>
              <%= form.text_field :first_name, class: "form-control", id: "first_name" %>
              <div class="error-message" id="error_first_name"></div>
            </div>
            <div class="form-group">
              <%= form.label :last_name, 'Last Name' %>
              <%= form.text_field :last_name, class: "form-control", id: "last_name" %>
              <div class="error-message" id="error_last_name"></div>
            </div>
          </div>

          <!-- Row Birthday and Gender -->
          <div class="form-row">
            <div class="form-group">
              <%= form.label :birthday, 'Birthday' %>
              <%= form.date_field :birthday, class: "form-control", id: "birthday" %>
              <div class="error-message" id="error_birthday"></div>
            </div>
            <div class="form-group">
              <%= form.label :gender, 'Gender' %>
              <div class="radio-group">
                <%= form.radio_button :gender, "Male", id: "gender_male" %>
                <%= form.label :gender_male, "Male", class: "label-gender", for: "gender_male" %>
                <%= form.radio_button :gender, "Female", id: "gender_female" %>
                <%= form.label :gender_female, "Female", class: "label-gender", for: "gender_female" %>
              </div>
              <div class="error-message" id="error_gender"></div>
            </div>
          </div>

          <!-- Row Email and Phone -->
          <div class="form-row">
            <div class="form-group">
              <%= form.label :email, 'Email' %>
              <%= form.email_field :email, class: "form-control", id: "email" %>
              <div class="error-message" id="error_email"></div>
            </div>
            <div class="form-group">
              <%= form.label :phone, 'Phone Number' %>
              <%= form.telephone_field :phone, class: "form-control", id: "phone", data: { controller: "phone", phone_target: "input" } %>
              <div class="error-message" id="error_phone"></div>
            </div>
          </div>

          <!-- Row Subject -->
          <div class="form-group">
            <%= form.label :subject, 'Subject' %>
            <%= form.select :subject, options_for_select([["Math", "Math"], ["Science", "Science"], ["Ruby", "Ruby"]]), prompt: "Choose option", class: "form-control", id: "subject" %>
            <div class="error-message" id="error_subject"></div>
          </div>

          <!-- Submit Button -->
          <div class="row-btn">
            <%= form.submit "Submit", id: "confirmCreate", class: "btn btn-submit", data: { action: "click->create#confirm_create" } %>
            <button type="button" id="cancelCreate" class="btn btn-no" data-action="click->create#close_modal">Cancel</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</body>

app/views/registers/list.html.erb
<body class="body-list" data-controller="create">
  <div class="container-list">
    <div class="row-btn" >
        <!-- Button to open the modal -->
    <button type="button" class="btn btn-add" data-action="click->create#show_modal">
      <i class="fas fa-user-plus"></i> Create Users
    </button>
    <%= render partial:"create_modal"%>
  </div>
    <div class="header">
    <!-- Heading for the user list -->
    <h1>Complete User List</h1>
    </div>
      
    <div class="filter-search">
      <%= form_with url: list_register_path, method: :get, local: true, html: { id: 'filter-form' } do %>
        <div class="search">
          <%= text_field_tag :search, params[:search], placeholder: "Search by name", id: 'search-input', class: 'filter-input' %>
          <%= submit_tag "Search", class: ' btn-search' %>
        </div>

        <div class="subject">
          <%= select_tag :subject, options_for_select(@subjects, params[:subject]), prompt: "All subjects", id: 'subject-select', class: 'filter-select' %>
        </div>
      <% end %>
    </div>
    <!-- List of all users -->
    <div class="user-list">
      <% if @registers.any? %>
        <ul class="user-cards">
        <% @registers.each do |register| %>
          <li class="user-card">
            <div class="user-info">
              <p class="name-info"><%= register.first_name %> <%= register.last_name %></p>
               <p><i class="fas fa-cake-candles"></i>
                  <% if register.birthday.present? %>
                    <%= register.birthday.strftime("%d %B %Y") %>
                  <% else %>
                    Not Available
                  <% end %>
                </p>
                <p><i class="fas fa-venus-mars"></i> <%= register.gender %></p>
               <p><i class="fas fa-envelope"></i>  <%= register.email %></p>
               <p><i class="fas fa-phone"></i> <%= register.phone %></p>
               <p><i class="fas fa-book"></i> <%= register.subject %></p>
            </div>

              <!-- Action Links -->
                <div class="action-links">
                  <%= link_to "Edit", edit_register_path(register), class: "btn btn-edit" %>

                  <%= form_with(model: register, url: register_path(register), method: :delete, local: true, html: { id: 'delete-form', class: 'delete-form' },data: { controller: "delete"}) do |form| %>
                    <button type="button" class="btn btn-delete" data-action="click->delete#show_modal">Delete</button>
                  <% end %>
                    <%= render partial:"delete_modal"%>
                </div>
          </li>
        <% end %>
        </ul>

      <% else %>
        <div class="empty-user">
          <i class="fa-solid fa-circle-info fa-3x"></i>
          <p >There are no users to display.</p>
        </div>
      <% end %>
    </div>
  </div>
</body>

app/views/registers/new.html.erb
<body class="body-register">
<div class="reg-form-container">
   
  <%= form_with model: @register, local: true, class: "reg-form" do |form| %>
   <h1>Create Users</h1>
  <!-- Row First Name and Last Name -->
  <div class="form-row">
    <div class="form-group">
      <%= form.label :first_name, 'First Name' %>
      <%= form.text_field :first_name, class: "form-control", id: "firstName" %>
      <!-- Message error first_name -->
        <% if @register.errors[:first_name].any? %>
       <div class="error-message">
        <%= @register.errors[:first_name].join(", ") %>
        </div>
       <% end %>
    </div>
    <div class="form-group">
      <%= form.label :last_name, 'Last Name' %>
      <%= form.text_field :last_name, class: "form-control", id: "lastName"%>
       <!-- Message error last_name -->
        <% if @register.errors[:last_name].any? %>
       <div class="error-message">
        <%= @register.errors[:last_name].join(", ") %>
        </div>
       <% end %>
    </div>
  </div>

  <!-- Row Birthday and Gender -->
  <div class="form-row">
    <div class="form-group">
      <%= form.label :birthday, 'Birthday' %>
      <%= form.date_field :birthday, class: "form-control", id: "birthday" %>
        <!-- Message error birthday -->
        <% if @register.errors[:birthday].any? %>
        <div class="error-message">
        <%= @register.errors[:birthday].join(", ") %>
        </div>
        <% end %>
    </div>
    <div class="form-group">
      <%= form.label :gender, 'Gender'%>
      <div class="radio-group">
        <%= form.radio_button :gender, "Male", id: "male" %>
        <%= form.label :gender_male, "Male",  class:"label-gender" ,for: "male" %>
        <%= form.radio_button :gender, "Female", id: "female" %>
        <%= form.label :gender_female, "Female", class:"label-gender" ,for: "female" %>
      </div>
      <!-- Message error gender -->
      <% if @register.errors[:gender].any? %>
      <div class="error-message">
      <%= @register.errors[:gender].join(", ") %>
      </div>
      <% end %>
    </div>
  </div>

  <!-- Row Email and Phone -->
  <div class="form-row">
    <div class="form-group">
      <%= form.label :email, 'Email' %>
      <%= form.email_field :email, class: "form-control", id: "email" %>
        <% if @register.errors[:email].any? %>
        <div class="error-message">
        <%= @register.errors[:email].join(", ") %>
        </div>
        <% end %>
    </div>
<div class="form-group">
  <%= form.label :phone, 'Phone Number' %>
  <%= form.telephone_field :phone, class: "form-control", id: "phone", data: { controller: "phone", phone_target: "input" } %>
  
  <% if @register.errors[:phone].any? %>
    <div class="error-message">
      <%= @register.errors[:phone].join(", ") %>
    </div>
  <% end %>
</div>

      </div>

  <!-- Row Subject -->
  <div class="form-group">
    <%= form.label :subject, 'Subject' %>
    <%= form.select :subject, options_for_select([["Math", "Math"], ["Science", "Science"],["Ruby", "Ruby"]]), prompt: "Choose option", class: "form-control", id: "subject" %>
      <% if @register.errors[:subject].any? %>
      <div class="error-message">
      <%= @register.errors[:subject].join(", ") %>
      </div>
      <% end %>
  </div>

  <!-- Submit Button -->
  <div class="form-group">
    <%= form.submit "Submit", class: "btn-submit" %>
  </div>
   
</div>
<body>
<% end %>

app/views/registers/show.html.erb
 <body class="body-show">
   
  <div class="container-show">
   
    <!-- User Details -->
    <div class="user-details" data-controller="delete">
 
        <%= link_to list_register_path, class: "btn-back-all-users" do %>
          <i class="fas fa-arrow-left"></i> Back
        <% end %>
  
      <h1><%= @register.first_name %> <%= @register.last_name %></h1>

      <div class="details-list">
        <p><i class="fas fa-cake-candles"></i>  
          <%= @register.birthday.strftime("%d %B %Y") if @register.birthday.present? %>
        </p>
        <p><i class="fas fa-venus-mars"></i> <%= @register.gender %></p>
        <p><i class="fas fa-envelope"></i>  <%= @register.email %></p>
        <p><i class="fas fa-phone"></i> <%= @register.phone %></p>
        <p><i class="fas fa-book"></i> <%= @register.subject %></p>
      </div>

      <!-- Action Links -->
      <div class="action-links">
        <%= link_to "Edit", edit_register_path(@register), class: "btn btn-edit" %>

        <%= form_with(model: @register, url: register_path(@register), method: :delete, local: true, html: { id: 'delete-form', class: 'delete-form' },data: { controller: "delete"}) do |form| %>
          <button type="button" class="btn btn-delete delete-button" data-action="click->delete#show_modal">Delete</button>
        <% end %>

      </div>

      <!-- Delete Confirmation Modal -->
      <div id="deleteConfirmationModal" class="modal-delete">
        <div class="modal-content-delete">
          <p>Are you sure you want to delete this user?</p>
          <div class="row-btn" >
             <button id="confirmDelete" class="btn btn-delete" data-action="click->delete#confirm_delete">Yes, Delete</button>
            <button id="cancelDelete" class="btn btn-no" data-action="click->delete#close_modal">No</button>
          </div>
        </div>
      </div>

    </div>
  </div>
</body>